### ISSUE TITLE
Sync path that works on Windows and macOS

### ISSUE THREAD

**Issue by marcvanbreemen** [JetClient/jet-client-support#108]
### Is your feature request related to a problem?

On Windows, I've set the sync path to f.e. "C:\Repo\Test\Shared\API". That path won't work when the repo is used on macOS.

I then tried to use a relative path, like: "..\Shared\API". That seems to work, as I see that the md is created in that folder.

However when If I use that same relative target folder in an other project, the data won't show.

### Describe the solution you'd like

A way to use a sync folder path that works on different machines / OS. Making the same API definition folder accessible to multiple projects (when they all point to the same sync folder).

### Additional context

n/a

**Comment by AntonShuvaev** [comment]
The JetClient project sync path isn't included in the sync files but is stored in `.idea/JetClient/state.xml`, which isn't typically shared in Git to keep it machine-specific. When opening the project on another machine, you'll need to use "Import JetClient project" and set the sync folder path for that machine.
