### ISSUE TITLE
[FEAT] run many requests in parallel

### ISSUE THREAD

**Issue by faelin** [JetClient/jet-client-support#110]
### Is your feature request related to a problem?

I am using the client to run a comprehensive regression-test suite against my API, which means there are over 1200 requests that are "Fired" per run (plus each request repeats several times due to timeout limitations). This makes the test run take a very long time.

### Describe the solution you'd like

I would like to be able to select tests to run "asynchronously", or some other way to mark that certain requests should be able to run in parallel.

**Comment by AntonShuvaev** [comment]
This is already supported. Some `jc` methods have async versions you can use to run requests in parallel:

- `testCase` → `testCaseAsync`
- `sendRequest` → `sendRequestAsync`
- `runRequest` → `runRequestAsync`
- `runFolder` → `runFolderAsync`
- `runTestSuite` → `runTestSuiteAsync`

You can find an example of parallel requests in the demo project: [JetClient-Demo](https://github.com/JetClient/JetClient-Demo). See this file for a specific example where all "Delete vet" requests run in parallel: [_TS_Delete vets.md](https://github.com/JetClient/JetClient-Demo/blob/master/.jetclient/petclinic/vet/_TS_Delete%20vets.md).

**Comment by faelin** [comment]
Oh, excellent! Sorry that I missed that 😓
