### ISSUE TITLE
JetClient - not able to add new requests

### ISSUE THREAD

**Issue by svaret** [JetClient/jet-client-support#112]
**Describe the bug**
No JetClient entry in the Tools menu. No JetClient tab, just a JetClient Tools Tab where I can't find any way to add a new request.

**Steps to reproduce**
Install JetClient plugin
Try to navigate to the JetClient plugin tab or Tools -> JetClient to add request

**Expected behavior**
Expecting to find the JetClient tab or as a menu entry under the Tools menu

**Environment information:**
- OS: macOS Ventura 13.6.9
- IDE version: PyCharm 2024.1.6 (Professional Edition). Build #PY-241.19072.16, built on August 8, 2024

- plugin version:
241.19072.10

**Comment by svaret** [comment]
![JetClient Tools](https://github.com/user-attachments/assets/1f1b5771-ae9d-4daa-b074-e7b38fc87d22)
![license](https://github.com/user-attachments/assets/0602dd17-0b50-4400-b75b-876df13ba5e8)
![Tools memu](https://github.com/user-attachments/assets/f7dc2704-22a6-42d7-932a-118f37bd59fb)

**Comment by AntonShuvaev** [comment]
Hi, there are three JetClient tool windows. The main tool window with the requests is now on the left side by default, but you can drag it back to the right if needed. The "JetClient Tools" window on the right handles Preview, Documentation, and Snippets, while the "JetClient Console" at the bottom shows request logs.

**Comment by svaret** [comment]
Thanks, I see that now. 

However, how do I add new requests?

![jetclient](https://github.com/user-attachments/assets/03271f41-b82d-46cd-908a-daba6179a0f4)

**Comment by svaret** [comment]
I found it now by myself. Closing issue
