### ISSUE TITLE
Tabbed field navigation

### ISSUE THREAD

**Issue by dan-sherwin** [JetClient/jet-client-support#28]
### Is your feature request related to a problem?

There is no problem related to this feature request.

### Describe the solution you'd like

In the Multipart Form editor, it would be handy to be able to tab to the next field.  So if I am typing in the Key field, I could hit Tab and the focus would move to the Value field.  If I am in the Value field and hit Tab, it would move focus to the type select field on the next line. If focus is on the Type select field, and you hit Tab, focus would move to the Key field.  That way when inputing form data with a number of fields, it would greatly increase efficiency rather than they way it is now where you have to move from the keyboard to the mouse, select the field, move from mouse to keyboard, and so on.

**Comment by AntonShuvaev** [comment]
Thanks for the suggestion. I'll do it in the next update.
